import type { Metadata } from "next";
import {ReactNode} from "react";
import Header from "@/components/Header/Header";
import TanStackProvider from "@/components/TanStackProvider/TanStackProvider";
import "./globals.css";


export const metadata: Metadata = {
  title: "NoteHub",
  description: "Generated by create next app",
};

export default function RootLayout({ children, modal }: { children: ReactNode; modal: ReactNode; }) {
  return (
    <html lang="en">
      <body>
        <TanStackProvider>
            <Header />
            <main className="container">
        {children}
        {modal}
        </main>
            </TanStackProvider>
      </body>
    </html>
  );
}
